name: deploy-train-lambda
on:
  push:
    branches:
      - main
    paths:
      - 'model_training_lambda/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup AWS
      run: |
          mkdir ./.aws
          touch ./.aws/credentials
          echo '${{ secrets.AWS_CREDENTIALS_FILE }}' > ./.aws/credentials
    - name: zip
      run: |
          cd model_training_lambda
          pip install --target . numpy==1.22.4 pandas==1.3.4 prophet==4.0
          zip -r train_lambda_function.zip *

    - name: sync to s3
      env:
        AWS_SHARED_CREDENTIALS_FILE: ./.aws/credentials
        AWS_PROFILE: default
        AWS_DEFAULT_REGION: us-east-2
      run: |
        aws s3 cp ./model_training_lambda/train_lambda_function.zip s3://mthisyamondol/disney_rides_scripts/train_lambda_function.zip
        aws lambda update-function-code --function-name disneymodeltrain --s3-bucket mthisyamondol --s3-key disney_rides_scripts/train_lambda_function.zip --region us-east-2

